GET http://localhost:4010/prefix00/aaa/bbb?aaaa=bbbb
Test-Header: {"xxxx": "zzz"}
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD&CCC=EEE

###
GET http://localhost:4010/prefix00/aaa/bbb?aaaa=bbbb
Content-Type: application/x-www-form-urlencoded

CCC=DDD&CCC=EEE

###
GET http://localhost:4010/prefix02/image/test

###
GET http://localhost:4010/prefix00/ccc/ddd
Content-Type: application/json

{
    "aaaa": "bbbb",
    "cccc":[
        "dddd",
        "eeee"
    ]
}

###
POST http://localhost:4010/prefix00/ddd/eee
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="params"
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD&CCC=EEE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
    "aaaa": "bbbb",
    "cccc":[
        "dddd",
        "eeee"
    ]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="sample1.png"
Content-Type: image/png

< ./test/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:4010/prefix00/ddd/eee
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/prefix01/fff/ggg/xxx/yyy
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/prefix01/hhh/iii/aaa/bbb
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: application/yaml

< ./test/samplev2.yaml


###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: application/yaml

< ./test/samplev3.yaml


###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="yaml"; filename="samplev3.yaml"
Content-Type: application/yaml

< ./test/samplev3.yaml

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="yaml"; filename="samplev3-2.yaml"
Content-Type: application/yaml

< ./test/samplev3.yaml

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
DELETE http://localhost:4010/control/endpoints/testtest

###
GET http://localhost:4010/prefix01/user/user%20name

###
POST http://localhost:4010/prefix01/user
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

### 
POST http://localhost:4010/prefix01/fff/ggg/xxx/yyy
Content-Type: application/xml

<aaa>
  <bbb>
   bbb
  </bbb>
</aaa>

###
PUT http://localhost:4010/prefix00/pet
Content-Type: application/json

{
    "id": 1245,
    "name": "NAMAE",
    "photoUrls": [
        "http://photo.co.jp"
    ]

}

###
PUT http://localhost:4010/prefix00/pet
Content-Type: application/xml

<Pet >
  <id >998</id>
  <Category >
    <id >1332</id>
    <name >CAT_NAME</name>
  </Category>
  <name >doggie</name>
  <photoUrl >
    <photoUrl >http://test.com/photo/xxxx</photoUrl>
    <photoUrl >http://test.com/photo/xxxx</photoUrl>
    <photoUrl >http://test.com/photo/xxxx</photoUrl>
  </photoUrl>
  <tag >
    <Tag >
      <id >9876</id>
      <name >Spotty</name>
    </Tag>
    <Tag >
      <id >9876</id>
      <name >Spotty</name>
    </Tag>
    <Tag >
      <id >9876</id>
      <name >Spotty</name>
    </Tag>
  </tag>
  <status >sold</status>
</Pet>

###
POST http://localhost:4010/prefix00/pet
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Pet>
	<id>0</id>
	<Category>
		<id>0</id>
		<name>string</name>
	</Category>
	<name>doggie</name>
	<photoUrl>
		<photoUrl>string</photoUrl>
	</photoUrl>
	<tag>
		<Tag>
			<id>0</id>
			<name>string</name>
		</Tag>
	</tag>
	<status>available</status>
</Pet>


###
GET http://localhost:4010/prefix00/pet/123

###
GET http://localhost:4010/prefix00/store/order/5

###
POST http://localhost:4010/control/debug/endpoints
Content-Type: application/json

{
    "fileName": "./test/samplev3.yaml"
}

###
DELETE http://localhost:4010/control/debug/endpoints
Content-Type: application/json

{
    "fileName": "./test/samplev3.yaml"
}


###
GET http://localhost:4010/control/endpoints

###
GET http://localhost:4010/control/endpoints/35f9a569-e8c3-47bc-9357-23dd48b51f32


###
POST http://localhost:4010/control/switch-routes
Content-Type: application/json

{
    "routes": "routes2"
}

###
GET http://localhost:4010/prefix04/aaa/bbb?aaaa=bbbb
Test-Header: {"xxxx": "zzz"}
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD&CCC=EEE

###
GET /
