GET http://localhost:4010/prefix00/aaa/bbb?aaaa=bbbb
Test-Header: {"xxxx": "zzz"}
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD&CCC=EEE

###
GET http://localhost:4010/prefix00/aaa/bbb?aaaa=bbbb
Content-Type: application/x-www-form-urlencoded

CCC=DDD&CCC=EEE

###
GET http://localhost:4010/prefix02/image/test

###
GET http://localhost:4010/prefix00/ccc/ddd
Content-Type: application/json

{
    "aaaa": "bbbb",
    "cccc":[
        "dddd",
        "eeee"
    ]
}

###
POST http://localhost:4010/prefix00/ddd/eee
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="params"
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD&CCC=EEE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
    "aaaa": "bbbb",
    "cccc":[
        "dddd",
        "eeee"
    ]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="sample1.png"
Content-Type: image/png

< ./test/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:4010/prefix00/ddd/eee
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/prefix01/fff/ggg/xxx/yyy
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/prefix01/hhh/iii/aaa/bbb
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: application/yaml

< ./test/samplev2.yaml


###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: application/yaml

< ./test/samplev3.yaml


###
POST http://localhost:4010/control/endpoints/testtest
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="yaml"; filename="samplev3.yaml"
Content-Type: application/yaml

< ./test/samplev3.yaml

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="yaml"; filename="samplev3-2.yaml"
Content-Type: application/yaml

< ./test/samplev3.yaml

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
DELETE http://localhost:4010/control/endpoints/testtest

###
GET http://localhost:4010/prefix01/store/inventory

###
POST http://localhost:4010/prefix01/user
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD
