GET http://localhost:4010/custom-web00/aaa/bbb?aaaa=bbbb
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD

###
GET http://localhost:4010/custom-web00/ccc/ddd
Content-Type: application/json

{
    "aaaa": "bbbb",
    "cccc":[
        "dddd",
        "eeee"
    ]
}

###
POST http://localhost:4010/custom-web00/ddd/eee
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="sample1.png"
Content-Type: image/png

< .test/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:4010/custom-web00/ddd/eee
Content-Type: application/x-www-form-urlencoded

AAA=BBB&CCC=DDD
